.PHONY: build

REPO  ?= denden047/deeprobotics

build:
	# git clone https://github.com/openai/mujoco-py.git
	cp mjkey.txt mujoco-py
	cd mujoco-py && docker build -t denden047/mujoco-py .
	docker push denden047/mujoco-py
	docker build -t $(REPO) .
	docker push $(REPO)

